### ISSUE TITLE
Voltlet Not Starting correctly

### ISSUE THREAD

**Issue by iceman73** [mcolyer/hassio-addons#2]
I added your Voltlet addon to my HASSIO running on UBUNTU, and I get the following errors when trying to start the addon:

/run.sh: line 7: jq: not found
/run.sh: line 8: jq: not found
/run.sh: line 9: jq: not found
Starting voltlet with parameters:
MQTT Broker =
MQTT User =
MQTT Password =

I sent the Broker, User and Pass, but I am assuming since it can find jq, even though Hassio supervisor has access to it, its not parsing the values.

Chris

**Comment by iceman73** [comment]
@mcolyer any ideas?

**Comment by mcolyer** [comment]
Sorry that I missed the previous comment, so when you run hassio within resin the base docket image includes jq. My guess is that somehow you are using a separate base image for docker. Can you see if modifying the docker file and adding jq via apkg fixes the issue for you?

**Comment by iceman73** [comment]
I tried that and it didn't seem to work. I am using hassio on Ubuntu, and I see jq in the supervisor, just the docker instance doesn't have jq available

**Comment by mcolyer** [comment]
Can you see if you clone down https://github.com/mcolyer/hassio-addons/blob/explict/voltlet/config.json (links to the voltlet folder on the `explict` branch) and put it in the local addons folder and then build the container - does it fix your problem? If it does then I'll integrate that change into master.

**Comment by iceman73** [comment]
@mcolyer unfortunately I get the same error in Hassio

/run.sh: line 7: jq: not found
/run.sh: line 8: jq: not found
/run.sh: line 9: jq: not found
Starting voltlet with parameters:
MQTT Broker =
MQTT User =
MQTT Password =
flag needs an argument: -mqtt-password
Usage of ./voltlet:
  -mqtt-broker string
    	The host and port of the MQTT broker (default "localhost:1883")
  -mqtt-password string
    	The MQTT broker password
  -mqtt-user string
    	The MQTT broker user

**Comment by mcolyer** [comment]
I'm at a loss of what to try next. What version of hassio are you using and can you link me to the directions you used to install hassio on ubuntu?

**Comment by iceman73** [comment]
I am using 0.68.1, and I just installed a brand new Ubuntu machine and still have the same issue..

I used this script
https://github.com/home-assistant/hassio-build/tree/master/install#install-hassio

**Comment by mcolyer** [comment]
Ah I see the error now, I still had an extra `image` attribute in the `config.json`. Can you remove the previous local addon I suggested you create and clone down https://github.com/mcolyer/hassio-addons/blob/explict/voltlet/ (the whole directory) again? It should then try to rebuild the container with `jq.
